// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4SgqvatKdMLzRCc8KlV7WsERj6Qzs0UQ',
    appId: '1:355310556058:android:d5fade5936acbf80532023',
    messagingSenderId: '355310556058',
    projectId: 'dearpos-c9533',
    storageBucket: 'dearpos-c9533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmETtrQZZ6GJjspj2Qjqqrbi9QPhKEzxo',
    appId: '1:355310556058:ios:c4fb9d1fb60b9bfe532023',
    messagingSenderId: '355310556058',
    projectId: 'dearpos-c9533',
    storageBucket: 'dearpos-c9533.firebasestorage.app',
    iosBundleId: 'com.mrfansi.dearpos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmETtrQZZ6GJjspj2Qjqqrbi9QPhKEzxo',
    appId: '1:355310556058:ios:c4fb9d1fb60b9bfe532023',
    messagingSenderId: '355310556058',
    projectId: 'dearpos-c9533',
    storageBucket: 'dearpos-c9533.firebasestorage.app',
    iosBundleId: 'com.mrfansi.dearpos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCktlH_wVDRpM9dN794c5uMupLxTHhgBus',
    appId: '1:355310556058:web:ba0ae96350c51eab532023',
    messagingSenderId: '355310556058',
    projectId: 'dearpos-c9533',
    authDomain: 'dearpos-c9533.firebaseapp.com',
    storageBucket: 'dearpos-c9533.firebasestorage.app',
    measurementId: 'G-3F7D5JYMDY',
  );
}
