// Mocks generated by Mockito 5.4.4 from annotations
// in app/test/features/product_management/domain/usecases/get_products_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:app/core/error/failures.dart' as _i5;
import 'package:app/features/product_management/domain/entities/product.dart'
    as _i6;
import 'package:app/features/product_management/domain/entities/product_bundle.dart'
    as _i8;
import 'package:app/features/product_management/domain/repositories/product_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i3.ProductRepository {
  MockProductRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getProducts() =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getProducts,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Product>> getProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProduct,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>.value(
            _FakeEither_0<_i5.Failure, _i6.Product>(
          this,
          Invocation.method(
            #getProduct,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Product>> createProduct(
          _i6.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProduct,
          [product],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>.value(
            _FakeEither_0<_i5.Failure, _i6.Product>(
          this,
          Invocation.method(
            #createProduct,
            [product],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Product>> updateProduct(
          _i6.Product? product) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>.value(
            _FakeEither_0<_i5.Failure, _i6.Product>(
          this,
          Invocation.method(
            #updateProduct,
            [product],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Product>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteProduct(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteProduct,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> bulkUploadProducts(
          _i7.File? file) =>
      (super.noSuchMethod(
        Invocation.method(
          #bulkUploadProducts,
          [file],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #bulkUploadProducts,
            [file],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> searchProducts(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchProducts,
          [query],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #searchProducts,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getProductsByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductsByCategory,
          [category],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getProductsByCategory,
            [category],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>> getLowStockProducts(
          int? threshold) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLowStockProducts,
          [threshold],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Product>>(
          this,
          Invocation.method(
            #getLowStockProducts,
            [threshold],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Product>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>> createBundle(
          _i8.ProductBundle? bundle) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBundle,
          [bundle],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>>.value(
                _FakeEither_0<_i5.Failure, _i8.ProductBundle>(
          this,
          Invocation.method(
            #createBundle,
            [bundle],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>> updateBundle(
          _i8.ProductBundle? bundle) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBundle,
          [bundle],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>>.value(
                _FakeEither_0<_i5.Failure, _i8.ProductBundle>(
          this,
          Invocation.method(
            #updateBundle,
            [bundle],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> deleteBundle(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBundle,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, bool>>.value(
            _FakeEither_0<_i5.Failure, bool>(
          this,
          Invocation.method(
            #deleteBundle,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, bool>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductBundle>>> getBundles() =>
      (super.noSuchMethod(
        Invocation.method(
          #getBundles,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductBundle>>>.value(
                _FakeEither_0<_i5.Failure, List<_i8.ProductBundle>>(
          this,
          Invocation.method(
            #getBundles,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i8.ProductBundle>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>> getBundle(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBundle,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>>.value(
                _FakeEither_0<_i5.Failure, _i8.ProductBundle>(
          this,
          Invocation.method(
            #getBundle,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i8.ProductBundle>>);
}
